# serviceAccountName is the name of the ServiceAccount Argo-CD will use to access the cluster
serviceAccountName: argocd-manager

# ingressUrl is the url used to access the CSDP runtime
# example https://some.domain.name
ingressUrl: <ingressUrl>

# csdpToken is the user's Personal Access Token
csdpToken: <csdpToken>

# contextName is the name of the kube context (in the local kubeconfig file) that connects to the target cluster
contextName: <contextName>

# server is the k8s cluster API endpoint url
# can be obtained by
#   CONTEXT_NAME=<TARGET_CONTEXT_NAME>
#   CLUSTER_NAME=$(kubectl config view --raw --flatten -o jsonpath='{.contexts[?(@.name == "'"${CONTEXT_NAME}"'")].context.cluster}')
#   kubectl config view --raw --flatten -o jsonpath='{.clusters[?(@.name == "'"${CLUSTER_NAME}"'")].cluster.server}'
server: <server>
