apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

images:
  - name: quay.io/codefresh/csdp-add-cluster
    newTag: 0.3.1

resources:
  - configmap.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - job.yaml
  - secret.yaml
  - serviceaccount.yaml

vars:
  - name: CSDP_ADD_CLUSTER_SECRET
    objref:
      apiVersion: v1
      kind: Secret
      name: csdp-add-cluster-secret
